### PR TITLE
feat(TON-1402): Add TONX Section

### PR DESCRIPTION
**Pull request by nashPOP**
## Summary
Add TONX Section

## Ticket(s)
https://tonfura.atlassian.net/browse/TON-1402
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot(s)
1440px
image
768px
image
375px
image

### Mockup
https://www.figma.com/file/TqGUSsSkA1HJL1P35NWlUz/TONX-landing?node-id=22%3A1123&mode=dev

### CODE REVIEW

**Comment by ernieyang09** [comment]
Screenshot 2024-04-03 at 8 37 56 PM

md should be 24px

**Comment by ernieyang09** [comment]
Screenshot 2024-04-03 at 8 38 10 PM

設成跟下面一樣的margin
(80px 48px)

**Review by ernieyang09 — APPROVED** [review]

**Comment by ernieyang09** [comment]
oh, yarn add lottie-react

**Comment by fdcaidev** [comment]
This pull request is being automatically deployed to Netlify.

 ✅ Preview: https://660d52997f6d27e6bb2c36da--tonx-landing-develop.netlify.app

**Pull request merged**
